# Generated by Django 4.2.4 on 2023-08-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artist_name', models.CharField(max_length=50)),
                ('main_colour', models.CharField(choices=[('Black', 'Black'), ('Dark Blue', 'Dark Blue'), ('Green', 'Green'), ('Grey', 'Grey'), ('Light Blue', 'Light Blue'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=20)),
                ('landscape', models.BooleanField()),
                ('actual_photo', models.ImageField(upload_to='static/photos')),
            ],
        ),
    ]
