# Generated by Django 4.2.4 on 2023-09-03 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APPfoto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='foto',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foto',
            name='actual_photo',
            field=models.ImageField(upload_to='APPfoto/static'),
        ),
    ]
