# Generated by Django 4.2.4 on 2023-09-04 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APPfoto', '0004_alter_foto_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='main_colour',
            field=models.CharField(choices=[('Black', 'Black'), ('Dark Blue', 'Dark Blue'), ('Green', 'Green'), ('Grey', 'Grey'), ('Light Blue', 'Light Blue'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=100),
        ),
        migrations.AlterField(
            model_name='foto',
            name='name',
            field=models.CharField(default='No name Given', max_length=50),
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(default='Questo utente non ha lasciato una recensione scritta, solo un voto.', max_length=250)),
                ('voto_positivo', models.BooleanField()),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='APPfoto.foto')),
                ('fotografo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotografo', to=settings.AUTH_USER_MODEL)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recensioni',
            },
        ),
        migrations.CreateModel(
            name='Acquisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiale', models.CharField(choices=[('Carta Fotografica', 'Carta Fotografica'), ('Tela', 'Tela'), ('Carta Standard', 'Carta Standard'), ('Lamiera Semplice', 'Lamiera Semplice'), ('Lamiera Premium', 'Lamiera Premium'), ('Puzzle', 'Puzzle')], max_length=100)),
                ('dimensioni', models.CharField(choices=[('10 x 15', '10 x 15'), ('12 x 18', '12 x 18'), ('13 x 19', '13 x 19')], max_length=100)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquirente', to=settings.AUTH_USER_MODEL)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Foto', to='APPfoto.foto')),
            ],
        ),
    ]
