# Generated by Django 4.2.4 on 2023-09-04 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APPfoto', '0005_alter_foto_main_colour_alter_foto_name_recensione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisto',
            name='acquirente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acquisto',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venduti', to='APPfoto.foto'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_scritte', to=settings.AUTH_USER_MODEL),
        ),
    ]
