# Generated by Django 4.2.4 on 2023-09-05 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APPfoto', '0006_alter_acquisto_acquirente_alter_acquisto_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='fotografo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to=settings.AUTH_USER_MODEL),
        ),
    ]
