# Generated by Django 4.2.4 on 2023-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPfoto', '0007_alter_recensione_fotografo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='prezzo'),
        ),
    ]
