# Generated by Django 4.2.4 on 2023-09-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPfoto', '0010_foto_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='created_at',
            new_name='creation_date',
        ),
    ]
