# Generated by Django 4.2.4 on 2023-09-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPfoto', '0012_acquisto_prezzo_alter_acquisto_dimensioni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisto',
            name='dimensioni',
            field=models.CharField(choices=[(0.0, '10 x 15   (+0.00)'), (2.0, '12 x 18   (+2.00)'), (3.0, '13 x 19   (+3.00)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='acquisto',
            name='materiale',
            field=models.CharField(choices=[(0.0, 'Carta Standard (+0.00)'), (1.0, 'Tela (+1.00)'), (2.0, 'Carta Fotografica (+2.00)'), (3.5, 'Puzzle (+3.50)'), (3.0, 'Lamiera Semplice (+3.00)'), (4.0, 'Lamiera Premium (+4.00)')], max_length=100),
        ),
    ]
