# Generated by Django 4.2.4 on 2023-09-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPfoto', '0013_alter_acquisto_dimensioni_alter_acquisto_materiale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisto',
            name='dimensioni',
            field=models.CharField(choices=[('10 x 15   (+0.00)', 0.0), ('12 x 18   (+2.00)', 2.0), ('13 x 19   (+3.00)', 3.0)], max_length=100),
        ),
    ]
