# Generated by Django 4.2.4 on 2023-09-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPfoto', '0014_alter_acquisto_dimensioni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisto',
            name='materiale',
            field=models.CharField(choices=[('Carta Standard (+0.00)', 0.0), ('Tela (+1.00)', 1.0), ('Carta Fotografica (+2.00)', 2.0), ('Puzzle (+3.50)', 3.5), ('Lamiera Semplice (+3.00)', 3.0), ('Lamiera Premium (+4.00)', 4.0)], max_length=100),
        ),
    ]
