# Generated by Django 4.2.4 on 2023-09-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPfoto', '0015_alter_acquisto_materiale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisto',
            name='dimensioni',
            field=models.CharField(choices=[('0.00', '10 x 15   (+0.00)'), ('2.00', '12 x 18   (+2.00)'), ('3.00', '13 x 19   (+3.00)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='acquisto',
            name='materiale',
            field=models.CharField(choices=[('0.00', 'Carta Standard (+0.00)'), ('1.00', 'Tela (+1.00)'), ('2.00', 'Carta Fotografica (+2.00)'), ('3.50', 'Puzzle (+3.50)'), ('3.00', 'Lamiera Semplice (+3.00)'), ('4.00', 'Lamiera Premium (+4.00)')], max_length=100),
        ),
    ]
