# Generated by Django 4.2.4 on 2023-09-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPfoto', '0016_alter_acquisto_dimensioni_alter_acquisto_materiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='acquisto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='APPfoto.acquisto'),
        ),
    ]
