# Generated by Django 4.2.4 on 2023-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPfoto', '0017_recensione_acquisto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recensione',
            name='voto_positivo',
        ),
        migrations.AddField(
            model_name='recensione',
            name='voto',
            field=models.PositiveIntegerField(default=6, max_length=1),
            preserve_default=False,
        ),
    ]
