# Generated by Django 4.2.4 on 2023-09-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPfoto', '0018_remove_recensione_voto_positivo_recensione_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='voto',
            field=models.PositiveIntegerField(),
        ),
    ]
